name: EnhancedGlistBridge
author: Wirlie
version: "2.0.0"
main: dev.wirlie.glist.spigot.EnhancedGlistSpigot
softdepend:
  - Essentials
  - PremiumVanish
  - SuperVanish
  - JetsAntiAFKPro
  - VanishNoPacket
commands:
  egls:
    usage: /<command>
    aliases: ["eglist-spigot", "enhancedglist-spigot"]
